theme = "ayu_dark"

[editor]
cursorline = true
bufferline = "always"
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.search]
smart-case = false

[editor.indent-guides]
render = true
character = "▏"

[editor.file-picker]
hidden = false

[keys.normal]
"\\" = { s = ":w", p = "file_picker", "/" = "toggle_comments" }

[keys.insert]
# "\\" = { s = ":w", p = "file_picker", "/" = "toggle_comments" }
# "\\" = { s = ["normal_mode", "command_mode", ":w"], p = ["normal_mode", ":w", "file_picker"] }

[keys.select]
"\\" = { "/" = "toggle_comments" }
