theme = "ayu_dark"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.search]
smart-case = false

[keys.normal]
"\\" = { s = ":w", p = "file_picker", "/" = "toggle_comments" }

[keys.insert]
"\\" = { s = ["normal_mode", ":w"], p = ["normal_mode", ":w", "file_picker"] }

[keys.select]
"\\" = { "/" = "toggle_comments" }
