[[language]]
name = "elixir"
auto-format = true
formatter = { command = "mix", args = ["format", "mix.exs", "-"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "babel"] }

[[language]]
name = "ruby"
auto-format = true
config = { solargraph = { diagnostics = true, formatting = false } }
formatter = { command = "rufo" , args = ["-x"] }

[[language]]
name = "rust"
auto-format = true